#+TITLE: Compilation 2025/2026 -- Journal du cours
#+AUTHOR: Adrien Guatto
#+EMAIL: guatto@irif.org
#+LANGUAGE: fr
#+OPTIONS: ^:nil p:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \hypersetup{hidelinks}
#+LATEX_HEADER: \usepackage[french]{babel}
# (org-latex-export-to-pdf)

* Cours 01 <2025-09-12>
** Présentation
   Voir les transparents dans
   [[file:cours-introduction.pdf][cours-introduction.pdf]].
** Introduction à la compilation : le micro-langage Marthe
   Le reste de la séance est consacré à la lecture et discussion d'un
   micro-langage de programmation, Marthe. Voir le fichier
   [[file:cours-01/marthe.ml][marthe.ml]].

   On s'arrête juste avant la compilation vers la machine abstraite.
** À préparer pour le prochain TP et le prochain cours
*** TODO Prochaine séance de travaux pratiques
    - Recommandé : venir avec son ordinateur portable, lundi
    - S'assurer que votre environnement de travail dispose d'un environnement de
      développement OCaml fonctionnel (compilateur OCaml, OPAM, dune).
*** TODO S'inscrire sur la liste de diffusion du cours
    https://listes.u-paris.fr/wws/info/m1.2025.compilation.info
*** TODO Prochaine séance de cours
    - Implémenter la gestion des commentaires dans ~marthe.ml~.
* Cours 02 <2025-09-17>
** Contenu de la séance
   On discute de la partie compilation dans le reste du fichier ~marthe.ml~.

   On découvre [[file:cours-flap.pdf][le compilateur flap]].
** Prochain TP
   Pensez à amener votre ordinateur portable.
* Cours 03 <2025-09-26>
** Cours
   On discute de l'analyse lexicale et syntaxique.

   Voir les [[file:cours-parsing.pdf][diapos]].
** Projet
   Le jalon 1 est publié.
* Cours 04 <2025-10-03>
  Voir les transparents au sujet de
  l'[[file:cours-interpretation.pdf][interprétation]].
* Cours 05 <2025-10-10>
  On continue à discuter de l'interprétation, jusqu'au début du traitement des
  références.
* Cours 06 <2025-10-17>
  On termine l'interprétation.

  On débute la discussion du [[file:cours-typage.pdf][typage]].
